### ISSUE TITLE
invalid frame case for cobs_inplace_decode

### ISSUE THREAD

**Issue by saltyJeff** [charlesnicholson/nanocobs#43]
See here for an executable version: https://godbolt.org/z/MdT5befeq

Driver Program:
```c++
#include "cobs.h"
#include <iostream>

using namespace std;
int main()
{
    char buf[] = {0x2, 0, 0};
    auto ret = cobs_decode_inplace(buf, sizeof(buf));

    cout << "returned COBS_RET_SUCCESS: " << (ret == COBS_RET_SUCCESS) << endl;

    cout << "buffer: " << hex << endl;
    for(int i = 0; i < sizeof(buf); i++)
    {
        cout << (int)(buf[i]) << " ";
    }
    cout << endl;
}
```

Output:
```
returned COBS_RET_SUCCESS: 1
buffer: 
5a 0 5a 
```

Expected Output:
Return `COBS_RET_ERR_BAD_PAYLOAD` since the input was invalid due to the intermediate 0 byte.

**Comment by charlesnicholson** [comment]
Thanks for reporting; I appreciate it, and sorry you hit this! I'll take a look later tonight.

**Comment by charlesnicholson** [comment]
Gotcha- the cobs decode functions don't validate the parts of the payload that aren't "pointed to" by previous zero-byte tokens. I did this mostly for performance, so that a subset of in-place decode payloads could be very fast and not have to touch every byte of the newly-arrived data.

I guess there are two ways to handle this:

1. Have all the cobs decode functions touch every byte in the payload and error out if they contain any internal zero-byte values.
2. Add another function called `cobs_validate(void const *buf, unsigned len)` (or something) that explicitly touches every byte of the encoded payload, ensures that no "pointer" bytes jump off the edge of the buffer _and_ that there are no internal zero bytes.

Option 2 preserves the "fast path", and in exchange is slightly wasteful because you visit the buffer twice- once to validate, and another to decode. But, without validation it's hard to trust that a buffer is correctly encoded- zero bytes that are jumped over probably indicate either corruption in transit, a bug or memory-stomping in the encoder, etc.

So I guess it makes the most sense to do option 1, as you suggest. I'll take a shot at it soon, thanks again for the report.

**Comment by saltyJeff** [comment]
I'm wrapping your library with my own, and what I have now is:

`cobs_decode_inplace(buf, strlen(buf)+1)`

**Comment by charlesnicholson** [comment]
I'm guessing you've thought this part through already, but I'm curious- if you're using `strlen` to find your frame delimiter, it's less likely but still possible to get a payload corruption that writes an actual `0x00` byte atop what would otherwise be a "pointer" byte. In that case, the COBS validation will succeed, and your corruption will go undetected. Do you encode a checksum or integrity check of some kind inside your frames as well?
