### ISSUE TITLE
Variable length decoding in place, where ends the data?

### ISSUE THREAD

**Issue by redfast00** [charlesnicholson/nanocobs#54]
We get in variable-length COBS encoded messages. In the README, there's an example with a fixed, 64-byte long buffer:

```c
char buf[64];

// You fill 'buf' with an encoded cobs frame (from uart, etc) that ends with 0x00.
unsigned const length = you_fill_buf_with_data(buf);

cobs_ret_t const result = cobs_decode_inplace(buf, length);
if (result == COBS_RET_SUCCESS) {
  // decoding succeeded, 'buf' bytes 0 and length-1 are COBS_SENTINEL_VALUE.
  // your data is in 'buf[1 ... length-2]'
} else {
  // decoding failed, look to 'result' for details.
}
```

However, if the buffer `buf` is variable-length and for example 10000 bytes long, I don't think the last valid byte will be at `length-2`. Is there an easy way to figure out the length of the decoded message? Maybe decode_inplace can in the `len` parameter take a pointer to an int, and update it to the decoded length?

**Comment by charlesnicholson** [comment]
Ah, the `_inplace` decode and encode are only guaranteed to work if the entire payload is <= `COBS_INPLACE_SAFE_BUFFER_SIZE` which you'll see is small. `_inplace` encoding is more interesting, because it's an optimization that guarantees you don't need an extra buffer. The big difference with the `_inplace` API is that it lets you encode in-place, which is possible only with very constrained payloads. `cobs_decode_inplace` is there for parity.

If you're only looking at decoding, and you have a 10,000 byte encoded buffer, you can still decode it "in-place" by simply calling `cobs_decode` with the `out_dec` and `enc` pointers pointing to the same address: byte 0 of the encoded buffer. 

As I type this up I realize the naming conventions aren't great, sorry about that. I'll brainstorm better names, also if you have any suggestions I'm all ears :)

**Comment by charlesnicholson** [comment]
An example:
```
char buf[16384];
unsigned encoded_len;
fill_buf_width_cobs_encoded_data(buf, &encoded_len); // your function
unsigned decoded_len;
cobs_decode(buf, encoded_len, buf, sizeof(buf), &decoded_len);
// at this point,  "buf" will contain the decoded payload, and "decoded_len" is the length of the decoded payload.
```

Is this what you're looking to achieve?

**Comment by redfast00** [comment]
Yes, thank you! Was indeed a bit confused that the `cobs_decode` also decodes inplace (but to your defense, this is mentioned in the README, I just overlooked it)

**Comment by charlesnicholson** [comment]
Glad it does what you want! I'll update the docs and try to think of better names for the `_inplace` versions; it's clearly a soft spot in the API.
