### ISSUE TITLE
`cobs_decode_inplace` does not work for >=254 consecutive non-zero bytes

### ISSUE THREAD

**Issue by TonalidadeHidrica** [charlesnicholson/nanocobs#58]
`cobs_decode_inplace` claims the decoded data sits in `1 ... size - 1`, but this is clearly wrong since if there is 254 consecutive non-zero bytes, the next byte (for the next header) shuold be truncated and not be replaced with 0.  Apparaently current implementation of `cobs_decode_inplace` doesn't seem to consider this case, and indeed [round-trip tests](https://github.com/charlesnicholson/nanocobs/blob/main/tests/test_wikipedia.cc#L132-L159) for such input data fails.

Aside from asking for a fix, is there any intention on why you didn't include `round_trip_inplace` in these two cases?  Adding them indeed made the test fail.

**Comment by charlesnicholson** [comment]
You are misunderstanding the library and misinterpreting a poorly-named function that I have to give a better name to. Please re-read https://github.com/charlesnicholson/nanocobs?tab=readme-ov-file#decoding-in-place, specifically:

```
There are two ways to decode COBS-encoded data in-place. One is simply by calling `cobs_decode` and pass your buffer to both the enc and out_dec parameters. Since COBS decoding never needs to revisit decoded bytes, and decoded payloads are always shorter than encoded payloads, this is guaranteed to work.
```

`cobs_decode_inplace` is the opposite of `cobs_encode_inplace` and is for tiny frames that can not have any code bytes _inserted_, which would lengthen the total payload. I need to rename these to `cobs_[en|de]code_tiny_frame`.

What you want to do can be achieved by simply calling `cobs_decode`.

The round-trip tests are explicitly not calling `cobs_decode_inplace` because the payloads are too large. This is by design.

**Comment by charlesnicholson** [comment]
The new v0.1.0 release and updated documentation hopefully makes all of this clearer!
